version: '3.4'

services:
  philomela.api:
    image: ${DOCKER_REGISTRY-}philomela.api:1.0
    build:
      context: .
      dockerfile: src/Philomela.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
